### PR TITLE
Lets add some tests

### PR DESCRIPTION
**Pull request by JamesFreeman**
# Awaiting Merge

- [x] Awaiting merge of #98 

# Todo

## Root
- [x] Oauth2Provider
- [ ] Webhook
- [ ] WebhookEvent
- [ ] XeroServiceProvider

## Config

- [x] Default Configs being set

## Routes
- [x] AuthorizationCallbackController
- [x] AuthorizationController

## Events

- [x] XeroAuthorized

## Oauth2CredentialManagers

- [x] ArrayStore (newly added - adding for simplified testing - users can use this for testing their apps and won't have to fake storage/cache system)
- [x] CacheStore
- [ ] FileStore

### CODE REVIEW

**Comment by JamesFreeman** [comment]
Hey, @hailwood,

Would you be able to have a review of this pr, I've had to make some changes to the core package to get the tests to work - just wanted to make sure you're happy with some of my changes.

- Upgraded to PHP 8.2+
- Upgraded to Laravel 10.x+
- Upgraded to PHPUnit 10.x+
- Upgrade to symfony/var-dumper 6.x+ (I was thinking we could in theory remove this as it doesn't seem to be used?
- Moving away from doc-blocks and now using types. 
- Added `Client` types - so I can mock out from the container.
- Renamed route file to `web.php` as recommended by testbench
- Added new ArrayStore for ease of testing in package and in end users apps.

**Comment by JamesFreeman** [comment]
It's also worth noting I've decided to go with PHPUnit for now, but happy to migrate to pest if you need me to.

**Comment by hailwood** [comment]
Thanks @JamesFreeman,
I'll review this in the coming week. Apologies I'm a bit delayed on all your excellent contributions.

**Comment by JamesFreeman** [comment]
I've pulled in develop to this branch, for some reason the tests aren't running - I'm not sure if you have to permit me to run them against the repo.

**Comment by hailwood** [comment]
Hey @JamesFreeman,
I'm wondering if it didn't run due to the conflicts?
There should be an option here for me to approve the workflow run but I don't see it at all.

Could you please fix the conflicts and we'll try again?

**Pull request closed without merging**
