### PR TITLE
[6.x] Allow for PHP 8.4 + Tests

### PR DESCRIPTION
**Pull request by JamesFreeman**
Work in progress

Going to leave this PR here until other packages are compatible with PHP 8.4 - but it looks like we're good at this point.

### CODE REVIEW

**Comment by JamesFreeman** [comment]
What do you think about dropping support for L10 in 6.x? 

Considering Laravel is only doing security fixes it might be a good time to drop support. If users are using L10, they can continue to use 5.x

**Comment by hailwood** [comment]
Yep, I'm happy with dropping support for L10 here.
I don't want us shoehorned by supporting older version of Laravel 👍

Which dependencies are currently failing the check?

**Comment by JamesFreeman** [comment]
It mostly looks like the lowest-preferred has the main issues - so when we'll need to bump the minimum version of packages when they become php8.4 compatible. 

- [ ] laravel/framework
- [ ] phpunit
- [ ] spatie/ray (looks like a transient dependency)

**Comment by JamesFreeman** [comment]
I'm not really sure the best way to get these tests to pass. It seems like the transient dependencies are causing issues on the prefer-lowest. 

Have you got any ideas? @hailwood

**Pull request closed without merging**
