### PR TITLE
Bring Develop inline with Master

### PR DESCRIPTION
**Pull request by JamesFreeman**

### CODE REVIEW

**Comment by hailwood** [comment]
@JamesFreeman I've merged this in, but it looks like we're still not quite in sync.
Would it be better if I just force push master to develop?

**Comment by JamesFreeman** [comment]
> @JamesFreeman I've merged this in, but it looks like we're still not quite in sync. Would it be better if I just force push master to develop?

Yeah, I'd say so. In theory, you could also just delete develop and recreate it?

**Comment by hailwood** [comment]
> > @JamesFreeman I've merged this in, but it looks like we're still not quite in sync. Would it be better if I just force push master to develop?
> 
> Yeah, I'd say so. In theory, you could also just delete develop and recreate it?

Ah, that closed all your PRs automatically.
Could you please resubmit them against the new develop branch?

**Comment by JamesFreeman** [comment]
No problems. I've done that now. :)

**Pull request merged**
